name: Action Runner For Test
run-name: ${{ github.actor }} is testing this action
on:
  push:
    branches:
      - main

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - run: echo "generating in ${{ runner.os }}"
      - run: echo "runnig by ${{ github.actor }}"
      
      - name: Trying throw something
        id: test_one
        run: echo passed
        continue-on-error: true

      - name: Testing if failure is error
        if: ${{steps.test_one.outcome}} == 'failure'
        run: 'echo test_one is error'

      - name: Testing if failure is error
        if: ${{steps.test_one.outcome}} == 'success'
        run: 'echo test_one not is error'