name: Action Runner For Test
run-name: ${{ github.actor }} is testing this action
on:
  push:
    branches:
      - main

jobs:
  Deploying:
    runs-on: ubuntu-latest
    steps:
      - run: echo "generating in ${{ runner.os }}"
      - run: echo "runnig by ${{ github.actor }}"
      
      - name: Trying throw something
        id: test_one
        run: exit 1
        continue-on-error: true

      - name: capture state OUTCOME
        run: echo "${{steps.test_one.outcome}}""

      - name: capture state OUTPUTS
        run: echo "${{steps.test_one.outputs}}"
        
        
      - name: capture state CONCLUSION
        run: echo "${{steps.test_one.conclusion}}"